/*
 * Generated DBSession Class AccessManagerSessionGenerated
 *
 * This is a placeholder for the file that will be generated by running
 * the generator script found in the same directory
 * This will be replaced by the generated code
 */

const path = require("path");

const DBSession = require("./../dbsession.js");

/*
 * AccessManagerSessionGenerated class declaration
 */
class AccessManagerGeneratedSession extends DBSession {

	constructor () {
		throw new Error("Please run the generator code first " + path.join(__dirname, "/generator.js"));
	}

}

module.exports = AccessManagerGeneratedSession;
